server:
  port: 8001

spring:
  application:
    # 服务名称
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hanlin.springcloud.entities

# eureka配置
eureka:
  client:
    # 是否将自己注册到eureka里
    register-with-eureka: true
    # 是否从eurekaserver抓取已有的注册信息，集群环境会用到
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/
