server:
  port: 8002

spring:
  application:
    # 服务名称
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hanlin.springcloud.entities

# eureka配置
eureka:
  client:
    # 是否将自己注册到eureka里
    register-with-eureka: true
    # 是否从eurekaserver抓取已有的注册信息，集群环境会用到
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群环境配置
  # actuator信息完善
  instance:
    instance-id: payment8002
    prefer-ip-address: true

# 用来展示项目的基本信息
info:
  author.name: hl.yuan
  app.name: springcloud
  server.port: ${server.port}
  application.name: ${spring.application.name}
