server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-PAYMENT   #匹配后提供服务的路由地址
          filters:
          - AddRequestParameter=name, hlyuan # 添加请求参数 name = hlyuan
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由
eureka:
  client:
    # 是否将自己注册到eureka里
    register-with-eureka: true
    # false代表不需要去检索服务,因为自己就是维护服务，这里设置为true，是因为网关需要检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
