server:
  port: 9090
eureka:
  client:
    register-with-eureka: false    #是否将自己注册到eureka里
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-order

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。

